apiVersion: 1

datasources:
- name: SystemLink Notebooks
  type: ni-slnotebook-datasource
  access: direct
  url: /
  version: 1
- name: SystemLink Systems
  type: ni-slsystem-datasource
  access: direct
  url: /
  version: 1
- name: SystemLink Tags
  type: ni-sltag-datasource
  access: direct
  url: /
  version: 1
- name: SystemLink Workspaces
  type: ni-slworkspace-datasource
  access: direct
  url: /
  version: 1