# pool:
#   name: DevCentral-Skyline
#   demands: npm

# pool:
#   vmImage: 'ubuntu-latest'

trigger:
  branches:
    include: master
  paths:
    include: systemlink-notebook-datasource/*

# Build & test

steps:
- script: npm ci
  displayName: Install deps (npm ci)

- script: npm run build
  displayName: Lint and build plugin

- script: npm run test
  displayName: Test plugin