pool:
  name: DevCentral-Skyline
  demands: npm

variables:
  working_dir: systemlink-notebook-datasource/

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - 'systemlink-notebook-datasource/*'

# Build & test

steps:
- script: npm ci
  displayName: Install deps (npm ci)
  workingDirectory: $(working_dir)

- script: npm run build
  displayName: Build and test plugin
  workingDirectory: $(working_dir)