pool:
  name: DevCentral-Skyline
  demands: npm

variables:
  working_dir: systemlink-notebook-datasource/

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - 'systemlink-notebook-datasource/*'

# Build & test

steps:
- script: npm ci
  displayName: Install deps (npm ci)
  workingDirectory: $(working_dir)
  env:
    NPM_TOKEN: $(NPM_TOKEN)

- script: npm run build
  displayName: Build and test plugin
  workingDirectory: $(working_dir)

- task: PublishTestResults@2
  displayName: 'Publish JUnit Test Results'
  inputs:
    testResultsFormat: JUnit
    testResultsFiles: '$(working_dir)/coverage/junit.xml'
    failTaskOnFailedTests: true