pool:
  name: DevCentral-Skyline
  demands: npm

variables:
  working_dir: systemlink-notebook-datasource/

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - 'systemlink-notebook-datasource/*'

# Build & test

steps:
- script: npm ci
  displayName: Install deps (npm ci)
  workingDirectory: $(working_dir)

- script: npm run build
  displayName: Lint and build plugin
  workingDirectory: $(working-dir)

- script: npm run test
  displayName: Test plugin
  workingDirectory: $(working-dir)